### ISSUE TITLE
Wrong variable used in storeFactory

### ISSUE THREAD

**Issue by aptiko** [MoonHighway/learning-react#11]
Hi,

https://github.com/MoonHighway/learning-react/blob/a9532f409d869c50aaa30e73ebee37ff54472699/chapter-08/color-organizer-redux/src/store/index.js#L27

I have a question in this code, which is also in Example 8-9 in the book:

```javascript
const storeFactory = (initialState=stateData) =>
    applyMiddleware(logger, saver)(createStore)(
        combineReducers({colors, sort}),
        (localStorage['redux-store']) ?
            JSON.parse(localStorage['redux-store']) :
            stateData
)
```

Is the last line correct? Shouldn't it be `initialState` instead? Otherwise what is the purpose of passing an `initialState` argument to the function?

**Comment by eveporcello** [comment]
Thanks for submitting this. The syntax is a little tricky here. Initial state comes from one of three places in this order:

localStorage - First we check localStorage. If there is state data there, we’ll use it.
initialState - If nothing is in localStorage, we’ll use the state that is sent via the storeFactory function.
stateData - If the first two aren’t provided, we’ll default to use the state data that is in the json file.

**Comment by aptiko** [comment]
I may be wrong of course, but afaics you aren't using (2). If the state isn't in `localStorage`, you go straight to using `stateData`, ignoring the state passed to `storeFactory()`.

**Comment by eveporcello** [comment]
Oh ok. I see what you mean. Just changed in the file. Thanks again!
