### ISSUE TITLE
Available in Apple iBooks?

### ISSUE THREAD

**Issue by AndresOchoaS** [MoonHighway/learning-react#17]

**Comment by eveporcello** [comment]
It's not available there unfortunately. Sorry about that. I know that some other O'Reilly books are but ours is not at this point. 

You can get it from Amazon or [Safari Books Online](https://www.safaribooksonline.com/library/view/learning-react-1st/9781491954614/). Safari has a free trial if you wanted to try it out! Let me know if you have any other questions.
