### ISSUE TITLE
"start": "open http://localhost:3000 & ./node_modules/.bin/httpster -p 3000 -d ./dist"

### ISSUE THREAD

**Issue by jhorgint** [MoonHighway/learning-react#18]
Error:  open' is not recognized as an internal or external command operable program or batch file 

I have installed Node 6.11.3 and Npm 3.10.10

this occurs on the "color-organizer"

**Comment by eveporcello** [comment]
Hi - thanks for the message. 

This error occurs when trying to run an 'open' command on a PC. To resolve this issue, we just updated the repository to add the **opener** npm package, which will work on PC and Mac.

To resolve, you can do one of the following:

**Option 1: Install opener package in the project**
1. You can run `npm install --save-dev opener`.
2. Change the "start" command to `"start": "opener http://localhost:3000 & httpster -p 3000 -d ./dist"`.

**Option 2: Copy the new package.json**
1. Copy this [package.json](https://github.com/MoonHighway/learning-react/blob/master/chapter-06/color-organizer/package.json) file into the color organizer project. 
2. Delete the node_modules folder.
3. Run `npm install && npm start`.

Let me know if any other questions come up.

**Comment by jhorgint** [comment]
**thanks a lot**
