### ISSUE TITLE
Question about styles

### ISSUE THREAD

**Issue by vlad-bezden** [MoonHighway/learning-react#2]
Hi Alex,

I enjoy reading your 'Learning React' book. Good content and great examples.

I have a question for you. Are you going to cover styles in this book? I could not find any information about  it.

Thanks and keep up a great work.

**Comment by MoonTahoe** [comment]
Hi Vlad,

Thanks for reviewing our early release and getting us some feedback. As far as CSS goes, we cover how to incorporate css and scss files in Chapter 5 during the webpack lesson. We also use inline styles for React components. It's not much, but we wanted the book to primarily focus on React and JavaScript.

Although we do not cover the syntax, most of the samples and examples in this book do incorporate [CSS](https://github.com/MoonHighway/learning-react/tree/master/chapter-05/recipe-app/stylesheets) files. The color-organizer incorporates [SCSS](https://github.com/MoonHighway/learning-react/tree/master/chapter-06/color-organizer/stylesheets) files. We do not dedicate any pages to dissecting these files in the book, but they are there for you to review.
