### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by eleach** [MoonHighway/learning-react#20]
in chapter 5 on "npm start" I get the following error:

>>>
24 verbose npm  v5.5.1
25 error code ELIFECYCLE
26 error errno 1
27 error recipe-app@1.0.0 start: `opener dist/index.html`
27 error Exit status 1
28 error Failed at the recipe-app@1.0.0 start script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]
<<<

I would like to run the examples. Thanks for any help.

**Comment by MoonTahoe** [comment]
1. Are you running in OSX or Windows?
2. What chapter/ lesson are you trying to run?

**Comment by eleach** [comment]
Hello,
Thanks for the reply. I'm on Linux (Ubuntu), in chapter 5, recipe-app. I will delete the chapter, carefully redo the steps, and see what happens.

**Comment by eleach** [comment]
Hello Mr. Banks,
I solved the problem. It had to do with starting the app on linux through a remote ssh connection.  The app looks for a browser and can't find one when started remotely.
I had no idea that "npm start" is so anxious to please that it wants to open a browser for me.

I appreciate all the great detail in your book, especially Chapter 5.
Something I noticed is that you say webpack.config.js is "right next to" index.js, but index.js is in the src folder, not the root folder. Maybe I'm not reading that part correctly.
Thanks again,
Ed
