### ISSUE TITLE
@chapter-07/color-organizer, color and backgroundColor of tilte don't change when rating a Color.

### ISSUE THREAD

**Issue by casinero** [MoonHighway/learning-react#26]
When rating a Color, the alert displays as expected, but color and background of `<h1>title</h1>` remain still, not changing as illustrated in the book. Looks like that setting `style` of the element in componentWillUpdate has no effect.
After clicking the alert, the background of the `<section>` element does turn white as illustrated.
I downloaded the repository in zip and `npm start`'ed this sample without any modification. My Chome's version is 64.

**Comment by MoonTahoe** [comment]
Give it a shot in Firefox, here's the link to the [sample](https://rawgit.com/MoonHighway/learning-react/master/chapter-07/color-organizer/dist/index.html).

I think google chrome changed the way it paints to the browser to make it more efficient...

**Comment by zavx0z** [comment]
> I think google chrome changed the way it paints to the browser to make it more efficient...

if you put a breakpoint to an alert, then the styles work.

**Comment by mpx2m** [comment]
I have the same problem. It doesn't work in Chrome.

**Comment by MoonTahoe** [comment]
This sample will not work in Chrome.
