### ISSUE TITLE
@chapter-07/01-mounting-lifecycle/02-mounting.html

### ISSUE THREAD

**Issue by VladBlow** [MoonHighway/learning-react#27]
Hello @MoonTahoe !

I have a question about this [line](https://github.com/MoonHighway/learning-react/blob/master/chapter-07/01-mounting-lifecycle/02-mounting.html#L77).

What do you mean by `error` in `<p>Error Loading Members: error</p>` after `:`.
In this place should be a visible error like word _error_ or error like error message? 
Cause I thought it was a message about the error and it should be in figure brace `{error}`.

Thank you for your book!

**Comment by MoonTahoe** [comment]
Thanks @VladBlow... it appears to be a typo. I fixed it. [solution](https://github.com/MoonHighway/learning-react/blob/e0346c72d5c5d643bb671b46f19b6ee189d26a1c/chapter-07/01-mounting-lifecycle/02-mounting.html#L77)

**Comment by VladBlow** [comment]
@MoonTahoe but why? 
```javascript
{error && <p>Error Loading Members: {error.message}</p>}
```
we can use lazy computing

**Comment by MoonTahoe** [comment]
It’s just to display any errors that have occured to the user on the screen. Anything that needs to be displayed in UI should be saved in state. We do not expect your users to check the console to figure out that something went wrong.

In a real project you actually have to do a lot more than this when an error occures. It should at least be cataloged and tracked in addition to displayed. If you are going to pop up an error measage that the user can clear you might as well save that error in state.
