### ISSUE TITLE
Spread operator causes ESLint error only in App.js

### ISSUE THREAD

**Issue by markgreenwood** [MoonHighway/learning-react#3]
The spread operator in this code [App.js line 62](https://github.com/MoonHighway/learning-react/blob/master/chapter-07/color-organizer/src/components/App.js#L62) keeps giving me the following ESLint error, yet the spread operator works fine in other places, e.g. [ColorList.js line 11](https://github.com/MoonHighway/learning-react/blob/master/chapter-07/color-organizer/src/components/ColorList.js#L11). The line/column numbers below are mine, not yours, but there's no significant difference in the code. I've actually cut-and-pasted that function directly and it still gives me the error.

file: 'file:///.../color-rater/src/Component/App.js'
severity: 'Error'
message: 'Parsing error: Unexpected token ...'
at: '37,11'
source: 'eslint'

Wondering why this is a problem in that one spot. If I replace App.js lines 61-64 with Object.assign({}, color, { rating }) it works as expected.

Loving early access to the e-book... thanks for providing it that way!

**Comment by markgreenwood** [comment]
Sorry... my bad. I just saw that the object spread operator is part of ES7 and it's probably not in my .eslintrc! The other places I was using it are all array spread operators.

**Comment by jordanpapaleo** [comment]
Do you need help with your eslint config?

Sent from my smallest computer

On Mar 25, 2017, at 8:39 PM, Mark Greenwood <notifications@github.com> wrote:

Sorry... my bad. I just saw that the object spread operator is part of ES7 and it's probably not in my .eslintrc! The other places I was using it are all array spread operators.

**Comment by markgreenwood** [comment]
Thanks for offering... looks like I got it. I just added
```
"ecmaFeatures": {
      "experimentalObjectRestSpread": true
}
```

**Comment by jordanpapaleo** [comment]
It looks like object spread should be in the [es2015 presets](https://babeljs.io/docs/plugins/preset-es2015/).  You should just be able to use the `babel-preset-es2015` dependency by itself.

Here is how I setup all of my projects lately (i do need to to do some package upgrades):

**dependencies/devDependencies**

- "babel-eslint": "7.0.0"
- "babel-plugin-transform-class-properties": "6.11.5"
- "babel-plugin-transform-decorators-legacy": "1.3.4"
- "babel-preset-es2015": "6.14.0"
- "babel-preset-react": "6.11.1"
- "babel-preset-stage-1": "6.13.0"
- "eslint": "3.12.0"
- "eslint-config-standard": "6.0.0"
- "eslint-plugin-react": "6.2.0"
- "standard": "8.6.0"

`.eslintrc`

```javascript
{
  "extends": [
    "plugin:react/recommended",
    "standard"
  ],
  "plugins": [
    "react"
  ],
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 7,
    "sourceType": "module",
    "ecmaFeatures": {
      "impliedStrict": true,
      "jsx": true
    }
  },
  "env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "ecmaFeatures": {
    "jsx": true,
    "es6": true,
    "classes": true
  },
  "globals": {
    "React": true
  },
  "rules": {}
}
```

`.babelrc`

```javascript
{
  "presets": ["es2015",  "stage-1", "react"],
  "plugins": [
    "react-hot-loader/babel",
    "transform-decorators-legacy",
    "transform-class-properties"
  ]
}
```

**Comment by markgreenwood** [comment]
Thanks for your help! Getting the right presets and plugins finally worked.
