### ISSUE TITLE
@chapter-11 <Redirect/> component can't work as expected

### ISSUE THREAD

**Issue by mpx2m** [MoonHighway/learning-react#30]
`<Redirect from="/history" to="/about/history" />`

https://rawgit.com/MoonHighway/learning-react/master/chapter-11/company-website/dist/#/history
can't be redirected to the link below
https://rawgit.com/MoonHighway/learning-react/master/chapter-11/company-website/dist/#/about/history

**Comment by MoonTahoe** [comment]
Interesting... thanks for pointing this out.

**Comment by MoonTahoe** [comment]
We are in the process of writing a 2nd edition to this book. All of the code in this repo will be updated.
