### ISSUE TITLE
Chapter 5 webpack.config.js no longer works with current webpack

### ISSUE THREAD

**Issue by Racheet** [MoonHighway/learning-react#31]
Both the webpack.config.js in the book, and the one [here](https://github.com/MoonHighway/learning-react/blob/master/chapter-05/recipe-app/webpack.config.js) fail in different ways when used with the current version of webpack.

The error I'm getting when running webpack in the chapter 5 recipie app folder is `Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize inste
ad.` and on the version in the book I get `Error: options/query cannot be used with loaders (use options for each array item)`

At this point I'm pretty stuck trying to continue through the examples. I've never used webpack before and don't know the api well enough to fix either issue.

**Comment by eveporcello** [comment]
Hi! This is true. The book uses webpack 3, so the repo uses the same version to match the [package.json](https://github.com/MoonHighway/learning-react/blob/master/chapter-05/recipe-app/package.json) in the book.

To get around this, you can run: `npm install webpack@3.6.0` to install at the appropriate version, or just run `npm install` in the project folder to ensure that everything is installed at the correct version.

In a future edition of the book, we'll upgrade to the latest version of webpack.

Let me know if any other questions come up. Thanks.
