### ISSUE TITLE
Chapter 9: Typo in source code?

### ISSUE THREAD

**Issue by dongbohu** [MoonHighway/learning-react#36]
In this line:
https://github.com/MoonHighway/learning-react/blob/796ebc37ceaac4a391dd3c20d16ce37f1e199338/chapter-09/color-organizer/src/store/index.js#L27

I think `stateData` should be `initialState`, which is the parameter of the function.

**Comment by MoonTahoe** [comment]
Thanks again. You seem to have an eye for this. We are in the process of writing a 2nd edition to this book. We're always looking for technical reviewers. If you are interested let me know.
