### ISSUE TITLE
Redundant lines?

### ISSUE THREAD

**Issue by dongbohu** [MoonHighway/learning-react#37]
In this file:
https://github.com/MoonHighway/learning-react/blob/master/chapter-07/05-higher-order-components/05-hocs.html

I don't think `componentWillReceiveProps` method in `MenuButton` class is needed:
https://github.com/MoonHighway/learning-react/blob/796ebc37ceaac4a391dd3c20d16ce37f1e199338/chapter-07/05-higher-order-components/05-hocs.html#L44
because this component's state is not being used at all.

**Comment by MoonTahoe** [comment]
Hmm. Wow. I wonder how that got there. We are in the process of writing a 2nd edition to this book we will be replacing this code. Thanks.
