### ISSUE TITLE
chapter 11. React Router

### ISSUE THREAD

**Issue by vlad-bezden** [MoonHighway/learning-react#4]
Hello,

I enjoy reading your book, and looking forward when it will be released. Right now I'm reading your book from safaribooksonline and I found that chapter 11 doesn't matches with code that you have. In the book you use react-router, but in your code examples on GitHub you use react-router-dom. Looks like react-router-dom is a new router v4.0 and it's a way to go. So my question is are you going to cover new react-router-dom in the book, and if so do you know when it will be updated on safaribooksonline?

Thank you very much and keep up a good work.

**Comment by eveporcello** [comment]
Hi Vlad - thanks so much for reading!

We just updated Chapters 11 and 12 to include Router 4. The repo is updated, but the book chapters are still in editing. I expect them to push those updates to Safari online really soon, likely in the next week or two. I will comment here and close the issue as soon as I see the update there.

Thanks again!

**Comment by vlad-bezden** [comment]
@eveporcello Awesome.

Thank you very much for such a great book and a hard work.

Cheers.

**Comment by eveporcello** [comment]
@vlad-bezden The update was pushed out to Safari, so you should see the latest router info in Chapters 11 & 12. 🎉 Thanks!

**Comment by vlad-bezden** [comment]
@eveporcello Thank you. Great job. I like your book. I learned a lot from it. Very well structured and written.
