### ISSUE TITLE
Empty array default props as undefined

### ISSUE THREAD

**Issue by chavab1** [MoonHighway/learning-react#43]
I'm following along with the book and I came across a problem.

On chapter 6, in the Color Organizer exercise, I keep getting the error `e is undefined`

It looks like it's referencing the default colors array and since it's empty it's complaining about the id. Because when I take out the reference to it it works but it renders two colors (an empty one for the first one) and then the one that I've selected. It then complains that the first color doesn't have a title, or color. 

I got it to work correctly by filtering the array to remove the empty item but I'd like to know what is causing this. I'm new to React so I want to make sure I'm doing things correctly.

Here is my code:

```
class ColorList extends Component {

	render() {
		const {colors, onRate, onRemove} = this.props
		return (
		    <div className="color-list">
		        {(colors.length === 0) ?
		            <p>No Colors Listed. (Add a Color)</p> :
		            colors.map(color =>
		                <Color key={color.id}
		                       {...color}
		                       onRate={(rating) => onRate(color.id, rating)}
		                       onRemove={() => onRemove(color.id)} />
					)
		        }
			</div>
		)
	}

}

ColorList.propTypes = {
    colors: PropTypes.array,
    onRemove: PropTypes.func,
	onRate: PropTypes.func    
}


ColorList.defaultProps = {
	colors: [],
	onRate: f=>f,
	onRemove: f=>f
}

export default ColorList
```

**Comment by MoonTahoe** [comment]
You shouldn't have an empty item in your color array. There is a bug somewhere else, I wonder what is causing this. Take a look at the `AddColorForm` and make sure it is getting the title and value for each color.
