### ISSUE TITLE
Chapter 6, color-organiser. The build process fails on node-sass

### ISSUE THREAD

**Issue by Leigh-M** [MoonHighway/learning-react#46]
npm ERR! Failed at the node-sass@4.5.3 postinstall script.

**Comment by Leigh-M** [comment]
For anyone with same issue, to correct this, delete "node-sass" from devDependencies.  From a terminal in the ../chapter-06/color-organiser folder do:  npm install node-sass --save-dev  
Then run npm start, it should rebuild correctly.   This is tested as working at node-sass 4.12.0, if any errors in future versions of node-sass install the 4.12.0 version

**Comment by MoonTahoe** [comment]
We are in the process of writing a 2nd edition, and we are updating all of the code in this repo.
