### ISSUE TITLE
Wrong Demo/Source code links in chapter 7

### ISSUE THREAD

**Issue by oxigen1um** [MoonHighway/learning-react#51]
In the 7-th chapter Higher Order Components section has a wrong link for 5-th example ( both Demo and Source code links are incorrect )

Instead of [proper link for demo](https://rawgit.com/MoonHighway/learning-react/master/chapter-07/05-higher-order-components/05-hocs.html) and [proper link for source code](https://github.com/MoonHighway/learning-react/blob/master/chapter-07/05-higher-order-components/05-hocs.html) used the wrong ones

Simply increment the value of the document in the link:

From this: `https://rawgit.com/MoonHighway/learning-react/master/chapter-07/05-higher-order-components/04-hocs.html` 

To that: `https://rawgit.com/MoonHighway/learning-react/master/chapter-07/05-higher-order-components/05-hocs.html`

**Comment by oxigen1um** [comment]
This issue related to #45 pull request

**Comment by eveporcello** [comment]
Sorry this happened when we were updating to v2. Thanks. Everything is at the second-edition branch now
