### ISSUE TITLE
Static id in code example chapter 5

### ISSUE THREAD

**Issue by dchisolm** [MoonHighway/learning-react#56]
Hi,

Checking out the preview book on O'Reilly, I ran across a small issue with the initial recipe.js example under "Break Components into Modules".

```
import React from "react";

function Recipe({name, ingredients, steps}) {
    return (<section id="baked-salmon"><h1>{name}</h1>
        <ul className="ingredients">        {ingredients.map((ingredient, i) => (
            <li key={i}>{ingredient.name}</li>))}      </ul>
        <section className="instructions"><h2>Cooking Instructions</h2>        {steps.map((step, i) => (
            <p key={i}>{step}</p>))}      </section>
    </section>);
}
```

Using this Recipe function, it appears every top level `<section>` would have an id of "baked-salmon". The examples leading up to this point "slugified" something for the id, but this example loves baked salmon specifically!

**Comment by eveporcello** [comment]
Yeah good call, we fixed this before it went to print. Thanks for sending this along!
