### ISSUE TITLE
[chapter-06/02-refs/09-stateless-default-arg] stateless default argument function property question

### ISSUE THREAD

**Issue by storenth** [MoonHighway/learning-react#57]
1. Is it equivalent of `defaultProps` in the stateless functional component's `onNewColor` definition?
```javascript
const AddColorForm = ({ onNewColor=f=>f }) => {};
AddColorForm.propTypes = {
  onNewColor: PropTypes.func
}
```
2. Can I refactor that statement as:
```javascript
const AddColorForm = ({ onNewColor=()=>{} }) => {};
AddColorForm.propTypes = {
  onNewColor: PropTypes.func
}
```

**Comment by kensan73** [comment]
Without running your code, it looks like you're asking essentially if

f => f is equivalent to () => {}

f => f is equivalent to function(f) { return f; }
() => {} is equivalent to function() { }

Depends on what you want onNewColor to do?

**Comment by storenth** [comment]
> Without running your code, it looks like you're asking essentially if
> 
> f => f is equivalent to () => {}
> 
> f => f is equivalent to function(f) { return f; }
> () => {} is equivalent to function() { }
> 
> Depends on what you want onNewColor to do?

@kensan73 I am asking to validate my solution to defaultProps in a functional component. If the property not provided we need to mock it without any errors because `f=>f` is equivalent to `() => {}` I guess in current the react context, and yes this is my core question.

**Comment by MoonTahoe** [comment]
@storenth , we use `f=>f` as a dummy function. All we need is a value that is invokable. `()=>{}`, `()=>null`, `function() { }`, they all work. The goal is to make sure the default type for `onNewColor` is a function, so when onNewColor is not supplied as a prop you can still invoke onNewColor() without breaking your code.

Why `f=>f`? No reason, we just think it looks good. For starters, it uses less characters than other choices. To me, the `f` means function. `const AddColorForm = ({ onNewColor=function() {}} ) => {};` Ahhhh. I just don't like it! `const AddColorForm = ({ onNewColor=f=>f }) => {};`, ok that's better 😜
