### ISSUE TITLE
Ch. 8: Sample "Incorporating React Markdown" not working as intended - missing 'login' property

### ISSUE THREAD

**Issue by dinaElagder** [MoonHighway/learning-react#65]
Readme file's content is not displayed on initialisation or when choosing a repo.

I followed the code in second edition book + sample in [sandbox](https://codesandbox.io/s/cocky-fog-h6xde?file=/src/App.js), both gave the same result.

Issue: RepoMenu component is expecting a **login prop,** but when used in UserRepositories component, the property is not passed and no calls are made to get the readme file data.

I **fixed** it and forked the sandbox with the [solution ](https://codesandbox.io/s/learning-react-ch-8-incorporating-react-markdown-km0xy?file=/src/UserRepositories.js) adding the login prop when using RepoMenu component.

**Comment by jvcorredor** [comment]
@dinaElagder Thanks a lot for this. I noticed that it's still rendering some html as text - mine does the same. Something to look at for the maintainers.

**Comment by eveporcello** [comment]
Hi @dinaElagder - thanks for this solution and the heads up. We just pushed this change. 

Thank you!
