### ISSUE TITLE
Missing `await` in async example. 

### ISSUE THREAD

**Issue by meatnordrink** [MoonHighway/learning-react#69]
This doesn't actually work, at least in two browser consoles I've tried: 
```
const getFakePerson = async () => {
  try {
    let res = await fetch("https://api.randomuser.me/?nat=US&results=1");
    let { results } = res.json();
    console.log(results);
  } catch (error) {
    console.error(error);
  }
};

getFakePerson();
```
The fourth line needs to be: 
```
let { results } = await res.json();
```

**Comment by MoonTahoe** [comment]
What page?

**Comment by meatnordrink** [comment]
I'm looking at the online edition, which doesn't have obvious page numbers; it's Chapter 2, JavaScript for React, and just under this text: 
> Notice that the getFakePerson function is declared using the async keyword. This makes it an asynchronous function that can wait for promises to resolve before executing the code any further. The await keyword is used before promise calls. This tells the function to wait for the promise to resolve. This code accomplishes the exact same task as the code in the previous section that uses then functions. Well, almost the exact same task…

In the section on asynchronous js.

**Comment by eveporcello** [comment]
Thanks @meatnordrink. I just pushed a change to fix this in the book. I like your solution or could do something like

```javascript
const getFakePerson = async () => {
  await fetch("https://api.randomuser.me/?nat=US&results=1").then(res => res.json()).then(console.log)
};
getFakePerson();
```
