### ISSUE TITLE
Uncaught SyntaxError: Unexpected token spread operator

### ISSUE THREAD

**Issue by cyuno** [MoonHighway/learning-react#7]
Running this on jsbin is fine but not on the chrome console:

let schools = [
    { name: "Yorktown"},
    { name: "Stratford" },
    { name: "Washington & Lee"},
    { name: "Wakefield"}
]

const editName = (oldName, name, arr) =>
    arr.map(item => {
        if (item.name === oldName) {
            return {
                ...item,
                name
            }
        } else {
            return item
        }
    })

let updatedSchools = editName("Stratford", "HB Woodlawn", schools)

console.log( updatedSchools[1] )
console.log( schools[1] )

I get the Uncaught SyntaxError: Unexpected token ...

Following this: http://stackoverflow.com/questions/38490804/spread-operator-in-react-throwing-error-of-unexpected-token did not work.

**Comment by jordanpapaleo** [comment]
The chrome console does not support all ES6 + features. You either have to transpile your code in a build process or use a browser babel polyfill.

**Comment by cyuno** [comment]
Hi. Thanks for responding.  Using this: http://stackoverflow.com/questions/42061415/how-to-use-object-spread-operator-in-chrome-dev-tools   worked for me, i.e. typing chrome://flags/#enable-javascript-harmony in the browser url field.
