### ISSUE TITLE
useEffect Sample with new react version misbehaves

### ISSUE THREAD

**Issue by pradiptakate** [MoonHighway/learning-react#71]
First, "Thanks for the really good book 'Leanring-React'".

I was trying the useEffect sample locally in my project. It was not working as shown in the book. Then I tried the sandbox of yours... It was working correctly but when I just updated package version to the latest, the sample though working but misbehaving.

After checking the checkbox, alert appears first and then the check mark is displayed.

Please see the sandbox. https://codesandbox.io/s/learning-react-useeffect-3-forked-udpqd

**Comment by MoonTahoe** [comment]
Since we wrote the book, Chrome got fancy and changed the wait it paints the UI. I am assuming it's an overall performance boost?

Give the sample a shot in Firefox...

**Comment by pradiptakate** [comment]
Thanks, Alex. It works fine in Firefox.
I think react version difference also causes the issue as with old react version, it works fine in Chrome as well.

P.S. I recommended the book to our Team.
