### ISSUE TITLE
RepositoryReadme component doesn't work

### ISSUE THREAD

**Issue by jawira** [MoonHighway/learning-react#72]
Hi, I tried the example from p.182 (Incorporating React Markdown) and I can't display Readme's  content.

My browser show the following error:

> Line 21:8:  React Hook useEffect has missing dependencies: 'loadReadme' and 'login'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

The readme file isn't displayed on CodeSandbox neither (https://codesandbox.io/s/cocky-fog-h6xde?file=/src/App.js), and `RepositoryReadme.js` has the following error:

![Screenshot from 2020-11-17 17-29-18](https://user-images.githubusercontent.com/496541/99417684-7d0ef780-28fa-11eb-809c-e573e418fad1.png)

Don't know if this matters but I'm using Firefox.

**Comment by martha-engineer** [comment]
Hello!

You could fix it by adding the login={login} property under the RepoMenu component in the UserRepositories.js file like shown below.

I hope this helps someone learning react!

UserRepositories.js:
```
import React from 'react';
import { Fetch } from './Fetch';
import RepoMenu from './RepoMenu';

export function UserRepositories({ login, selectedRepo, onSelect = f => f }) {
	return (
		<Fetch
			uri={`https://api.github.com/users/${login}/repos`}
			renderSuccess={({ data }) => (
				<RepoMenu
					repositories={data}
					login={login}
					selectedRepo={selectedRepo}
					onSelect={onSelect}
				/>
			)}
		/>
	);
}
```

**Comment by fpigeonjr** [comment]
Thanks @martha-softwaredeveloper this worked for me.
My `<RepoMenu>` was missing the `login` prop.
