### ISSUE TITLE
Error in sample code

### ISSUE THREAD

**Issue by jersearls** [MoonHighway/learning-react#8]
Hey there, noticed an error in this code snippet. Won't run, wanted to bring it to your attention. 

Love the book!!!

http://jsbin.com/gapoxa/9/edit?js,console

**Comment by rsachdeva** [comment]
@jersearls choose ES6 in drop down - screenshot attached.
![screen shot 2017-05-26 at 11 41 34 am](https://cloud.githubusercontent.com/assets/232903/26503985/765fb15e-4208-11e7-99bd-df5307fa1f17.png)

**Comment by jersearls** [comment]
Ah, awesome! Thanks!!

**Comment by rsachdeva** [comment]
You are welcome 👍
