### ISSUE TITLE
Running Example of Color Organizer download

### ISSUE THREAD

**Issue by adylol** [MoonHighway/learning-react#88]
Hi there,
is there an updated running example of the color organizer which i can download like in the first edition of the book?
I am completely confused about only having links to demo pages and not the full project.
Best regards,
Andreas

**Comment by eveporcello** [comment]
Hello @adylol - there are links to the second edition Color Organizer here in CodeSandbox: https://github.com/MoonHighway/learning-react/tree/second-edition/chapter-06

If you'd like a local version, you can fork the project and export with GitHub. [Instructions here](https://www.developerhandbook.com/parcel.js/set-up-react-project-parceljs/#:~:text=Save%20your%20project%20directly%20to,in%20with%20your%20GitHub%20account.&text=Give%20the%20project%20a%20name,GitHub%20in%20the%20normal%20way)
